[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "echo 'Building Leptos Portal...'"]

[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"

[watch]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 3002
open = false
